### ISSUE TITLE
零偏误差是否应该重新置0

### ISSUE THREAD

**Issue by zhchyang2004** [yandld/nav_matlab#1]
你好!

这里的零偏误差是否应该重新置0? 即在71行增加err_state(4:6)=0;
https://github.com/yandld/nav_matlab/blob/master/library/nav_lib/ahrs_test/ahrs_test.m#L71

谢谢!

**Comment by yandld** [comment]
您好， 如果零偏误差每次被反馈回去，那么就需要置0， 如果不反馈，就不置0. 反不反馈需要看你零偏误差估计的准不准，和很多因素有关系，比如器件的精度，工作时间，工况等等。
