### ISSUE TITLE
关于缺少函数ch_qintg的问题

### ISSUE THREAD

**Issue by tnt211702** [yandld/nav_matlab#2]
您好，我下载了开源代码并运行了ahrs_test.m，也添加lib到路径中，却依然报错“函数或变量 'ch_qintg' 无法识别。”请问您能上传这个函数吗？

以及我运行了UWB与IMU结合的实例画图，为何最终坐标只有实际的运行轨迹，而没有滤波之后的结果？（如下图所示https://imgchr.com/i/r5H1TH

本人是刚开始进行IMU+UWB室内定位项目的学生，看了您的源码之后受益良多，但有以上几个问题希望能得到解答，谢谢！

**Comment by yandld** [comment]
我最近就会更新，换了一个函数名，你24小时候再pull一下
