### ISSUE TITLE
关于函数或变量 'vnorm' 无法识别的问题

### ISSUE THREAD

**Issue by tenyee-space** [yandld/nav_matlab#3]
您好，我下载了您的zip代码文件，在运行uwb_imu_fusion_test时，我运行了init.m文件，但仍然提示函数或变量 'vnorm' 无法识别。请问是缺少这个函数吗

**Comment by yandld** [comment]
安装 2020版本 的 rctobsolete 工具箱：
C:\Program Files\Polyspace\R2020a\toolbox\robust\rctobsolete\mutools\commands
