### ISSUE TITLE
关于“MeasureNoiseVariance”这一常量的来源

### ISSUE THREAD

**Issue by tnt211702** [yandld/nav_matlab#4]
您好！

在您的IMU_UWB的项目的主程序中有这样一个常量表示的UWB测量噪声的方差：
MeasureNoiseVariance = [2.98e-03, 2.9e-03,1.8e-03, 1.2e-03, 2.4e-03];  %%%%  UWB Ranging noise

请问这个值是怎么得到的呢？是在静止的状态下长时间测量吗？

然后，同样是这个项目中，我有点不太理解其引用的gnss_imu_local_tan_example_settings这个函数中所设定的初始值为何是那样，比如加速度计与陀螺仪的噪声、偏置，还有速度位置均设置为100等等，这些也是在之前就已经校准得到的吗？

如果有方便的话劳烦您解决一下我的疑问，谢谢！

**Comment by yandld** [comment]
MeasureNoiseVariance  这个其实就是经验值


然后，同样是这个项目中，我有点不太理解其引用的gnss_imu_local_tan_example_settings这个函数中所设定的初始值为何是那样，比如加速度计与陀螺仪的噪声、偏置，还有速度位置均设置为100等等，这些也是在之前就已经校准得到的吗？
：这些说白了都是经验值，和初值。都不是测量出来的。 你加我微信说吧 15701256050
